# Generated by Django 2.1.8 on 2019-06-02 19:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190527_1555'),
        ('resources', '0002_auto_20190528_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCheckForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('doi', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('file', models.FileField(upload_to='papers/', verbose_name='上传的论文')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExpertProfile')),
            ],
        ),
    ]
