# Generated by Django 2.1.8 on 2019-06-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_papercheckform'),
    ]

    operations = [
        migrations.AddField(
            model_name='papercheckform',
            name='isCheck',
            field=models.BooleanField(default=False, verbose_name='是否被审核过'),
        ),
        migrations.AddField(
            model_name='papercheckform',
            name='isPass',
            field=models.BooleanField(default=False, verbose_name='是否通过'),
        ),
    ]
