# Generated by Django 2.1.8 on 2019-06-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='是否为管理员'),
        ),
    ]
