# Generated by Django 2.1.8 on 2019-05-24 18:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertCheckForm',
            fields=[
                ('formID', models.AutoField(primary_key=True, serialize=False, verbose_name='专家认证申请表单编号')),
                ('isPass', models.BooleanField(default=False, verbose_name='是否通过')),
                ('reason', models.TextField(verbose_name='管理员意见')),
                ('adminID', models.IntegerField(verbose_name='管理员ID')),
                ('intro', models.TextField(verbose_name='个人简介')),
                ('constitution', models.CharField(max_length=255, verbose_name='所在机构')),
                ('realName', models.CharField(max_length=255, verbose_name='真实姓名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='申请时间')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '专家认证申请表单',
                'verbose_name_plural': '专家认证申请表单',
            },
        ),
    ]
