# Generated by Django 2.1.8 on 2019-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_expertcheckform'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertcheckform',
            name='isCheck',
            field=models.BooleanField(default=False, verbose_name='是否被审核过'),
        ),
    ]
