# Generated by Django 2.1.8 on 2019-06-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertcheckform',
            name='expertID',
            field=models.CharField(max_length=255, null=True, verbose_name='专家在ES中的id'),
        ),
    ]
