# Generated by Django 2.1.8 on 2019-05-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_expertcheckform_ischeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertcheckform',
            name='adminID',
            field=models.IntegerField(null=True, verbose_name='管理员ID'),
        ),
    ]
