# Generated by Django 2.1.8 on 2019-06-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_expertcheckform_expertid'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='expertID',
            field=models.CharField(default='9000000000000', max_length=255, verbose_name='专家在ES中的id'),
        ),
    ]
