# Generated by Django 2.1.8 on 2019-05-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190524_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertprofile',
            old_name='intro',
            new_name='introduction',
        ),
    ]
