# Generated by Django 2.1.8 on 2019-05-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190526_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertcheckform',
            old_name='intro',
            new_name='introduction',
        ),
    ]
