# Generated by Django 2.1.8 on 2019-05-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190526_2040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('userID', 'followID')},
        ),
    ]
